### ISSUE TITLE
[1.15.2] One-shelf at a time Config

### ISSUE THREAD

**Issue by mr-poyo** [Phylogeny/BoundTotems#1]
Love this mod. It's very underrated. I can tell a lot of work was put into it!

Currently, you can bind yourself to as many shelves as you like and they work perfectly. For balancing, would it be possible to have a config option to only bind to one-shelf at a time? After you run out of totems in a shelf, you will either A) have to put more totems in, or B) bind yourself to a different shelf. 

Thanks for considering!

**Comment by Phylogeny** [comment]
Thank you. Yes, I can add a config that sets the max number of simultaneously bound shelves. So, the question is; what should happen when one tries to bind a shelf after one has reached the maximum number (whether the max is 1, or anything else). Possibilities:
1. Disallow the binding and destroy the self when the lightning strikes, in the same way as if the entity is too far away.
2. Allow the binding to occur, but overwrite the bound shelf (or one of the bound shelves, if the max is greater than one) to the new one. The question then is what to do with the previously bound one. Possibilities:
   1. The shelf could be destroyed, but the totems inside would be dropped, and would eventually despawn.
   2. The shelf could be burned/converted to a non-functional charred version that you can't place additional totems into. You would then be able to find and break it to get you're unused totems back.

I'm thinking 2(ii) is best. Let me know what you think.

**Comment by mr-poyo** [comment]
I think both options in (2) are better than (1).

**Option 1** - would bring another problem - "What if the player's previous shelves are inaccessible (lost, or some other means)?" Probably a workaround for it, but just seems like the other options are better. This would definitely be the fastest solution.

**Option 2(i)** - This option is also a fast solution. Seems the most hardcore out of the bunch, but it makes sense.

**Option 2(ii)** - This option seems the most polished in terms of quality content. I like this one a lot. And keeps it fair for players who may not like the idea of possibly losing hard-earned totems.

For options listed in (2), One obstacle might be destroying/burning a shelf in an unloaded chunk. It's quite possible a player might create a shelf far away from the other shelves. 

Anyways, I really like your ideas. I'll be keeping an eye!

**Comment by Phylogeny** [comment]
Excellent, I'll go with 2(ii) then. And unloaded chunks shouldn't be a problem; I already load currently unloaded dimensions/chunks to check for shelf blocks and use/remove totems from shelf tile entities, so additionally changing a shelf blockstate shouldn't be a problem.
